{
    "openapi": "3.0.1",
    "info": {
        "title": "Line Items",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "When creating a set of quotes for sales reps to send to potential buyers, use this API to add goods and services to the quotes.",
        "x-hubspot-related-documentation": [
            {
                "name": "Line Items Guide",
                "url": "https://developers.hubspot.com/beta-docs/guides/api/crm/objects/line-items"
            }
        ],
        "x-hubspot-introduction": "Use the line items API to add instances of products to deals and quotes. You can create line items from existing products or create them as custom line items with no product attached."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/objects/line_items"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/batch/read": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Read line items by ID or property",
                "operationId": "post-/crm/v3/objects/line_items/batch/read_read",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    }
                ],
                "description": "Returns a batch of line items matching the provided internal IDs or unique property values, with partial success indicated by a 207 response."
            }
        },
        "/{lineItemId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Retrieve a line item by ID",
                "description": "Read an Object identified by `{lineItemId}`. `{lineItemId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/line_items/{lineItemId}_getById",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Archive a line item by ID",
                "description": "Move an Object identified by `{lineItemId}` to the recycling bin.",
                "operationId": "delete-/crm/v3/objects/line_items/{lineItemId}_archive",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Update a line item by ID",
                "description": "Perform a partial update of an Object identified by `{lineItemId}`. `{lineItemId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/crm/v3/objects/line_items/{lineItemId}_update",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    }
                ]
            }
        },
        "/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Archive a batch of line items by ID",
                "operationId": "post-/crm/v3/objects/line_items/batch/archive_archive",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    }
                ],
                "description": "Archives the specified batch of line items by ID, returning no content on success."
            }
        },
        "/batch/create": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create a batch of line items",
                "operationId": "post-/crm/v3/objects/line_items/batch/create_create",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    }
                ],
                "description": "Returns a batch of newly created line item objects, including their IDs and properties. Returns 207 for partial success."
            }
        },
        "/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Update line items by ID or property",
                "operationId": "post-/crm/v3/objects/line_items/batch/update_update",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    }
                ],
                "description": "Returns the updated batch of line item objects identified by internal ID or unique property values. Returns 207 for partial success."
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "List a page of line items",
                "description": "Read a page of line items. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/line_items_getPage",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create a line item",
                "description": "Create a line item with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard line items is provided.",
                "operationId": "post-/crm/v3/objects/line_items_create",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    }
                ]
            }
        },
        "/batch/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Upsert line items by property",
                "description": "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
                "operationId": "post-/crm/v3/objects/line_items/batch/upsert_upsert",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.write"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.write"
                        ]
                    }
                ]
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Search"
                ],
                "operationId": "post-/crm/v3/objects/line_items/search_doSearch",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.objects.line_items.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.line_items.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ],
                "description": "Returns a paginated list of line items matching the specified search criteria and filters.",
                "summary": "Search line items"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets",
                            "crm.objects.custom.read": "View custom object records",
                            "e-commerce": "e-commerce",
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}